<?php

namespace Database\Seeds\Custom;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Seeder1591797244 extends Seeder
{
    public function run()
    {

        $num = 1;
        $num_ = 1;
        $categoryIdsToSeed = array(
            1,
            1,
            1,
            1,
            1,
            2,
            2,
            2,
            3,
            3,
            3,
            3,
            3,
            3,
            4,
            5,
            5,
            5,
            5,
            5,
            6,
            6,
            6,
            6,
            6,
            11,
            9,
            9,
            14,
            14,
            8,
            1,
            8,
            14,
            14,
            14,
            12,
            1,
            14,
            1,
            4,
            5,
            12,
            4,
            8,
            5,
            5,
            7,
            7,
            7,
            7,
            7,
            5,
            1,
            7,
            13,
            14,
            14,
            1,
            1,
            12,
            7,
            13,
            14,
            5,
            11,
            9,
            5,
            5,
            4,
            9,
            9,
            10,
            3,
            3,
            3,
            3,
            3,
            12,
            3,
            8,
            9,
            9,
            8,
            8,
            8
        );


        $permissionTooltipsToSeed = array(
            'class-list_tooltip',
            'class-show_tooltip',
            'class-create_tooltip',
            'class-edit_tooltip',
            'class-show_tooltip',
            'class-delete_tooltip',
            'contact-show_tooltip',
            'contact-delete_tooltip',
            'payment-list_tooltip',
            'payment-create_tooltip',
            'payment-delete_tooltip',
            'payment-plan-list_tooltip',
            'payment-plan-create_tooltip',
            'payment-plan-delete_tooltip',
            'schedule-list_tooltip',
            'student-list_tooltip',
            'student-create_tooltip',
            'student-show_tooltip',
            'student-edit_tooltip',
            'student-delete_tooltip',
            'teacher-list_tooltip',
            'teacher-show_tooltip',
            'teacher-create_tooltip',
            'teacher-edit_tooltip',
            'teacher-delete_tooltip',
            'attendance-add_tooltip',
            'Role-Management_tooltip',
            'User-Management_tooltip',
            'calendar_tooltip',
            'reservation-list_tooltip',
            'school-settings_tooltip',
            'cancel-class_tooltip',
            'user-settings_tooltip',
            'course_tooltip',
            'library_tooltip',
            'test_tooltip',
            'assessment_tooltip',
            'class-category_tooltip',
            'event_tooltip',
            'calendar-hide-full-class_tooltip',
            'schedule-details_tooltip',
            'take-student-test_tooltip',
            'take-assessment_tooltip',
            'schedule-add_tooltip',
            'email-settings_tooltip',
            'student-impersonate_tooltip',
            'student-map_tooltip',
            'todo-mytodos_tooltip',
            'todo-list_tooltip',
            'todo-create_tooltip',
            'todo-edit_tooltip',
            'todo-delete_tooltip',
            'student-search_tooltip',
            'class-usage_tooltip',
            'todo-progress_tooltip',
            'activity-logs_tooltip',
            'allow-reservation-on-past-classes_tooltip',
            'children_tooltip',
            'st-classes_tooltip',
            'st-class-details_tooltip',
            'st-assessments_tooltip',
            'todo-progress-details_tooltip',
            'dev-logs_tooltip',
            'stats_tooltip',
            'waitlisted-students_tooltip',
            'control-attendance_tooltip',
            'manage-tags_tooltip',
            'view-student-tags_tooltip',
            'edit-student-tags_tooltip',
            'edit-schedule_tooltip',
            'manage-availability-selection-calendars_tooltip',
            'manage-availability-timeslots_tooltip',
            'view-availability-responses_tooltip',
            'payment-settings_tooltip',
            'payment-mark-as-paid_tooltip',
            'payment-edit_tooltip',
            'st-payments_tooltip',
            'manage-monthly-payments_tooltip',
            'edit-assessment-response_tooltip',
            'accounting-payments_tooltip',
            'schedule-settings_tooltip',
            'manage-school-off-days_tooltip',
            'manage-zoom-meetings-for-class_tooltip',
            'line-settings_tooltip',
            'lesson-settings_tooltip',
            'terminal-settings_tooltip'
        );

        foreach ($categoryIdsToSeed as $categoryId){
            DB::table('permissions')
                ->where('id',$num)
                ->update([
                    "categoryId" => $categoryId,
                    'permissionTooltip' => 'class-list_tooltip',
            ]);
            $num++;
        }

        foreach ($permissionTooltipsToSeed as $permissionTooltip){
            DB::table('permissions')
                ->where('id',$num_)
                ->update([
                    'permissionTooltip' => $permissionTooltip,
            ]);
            $num_++;
        }

    }
}